DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS game;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE
);

CREATE TABLE game (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  player_id INTEGER,
  created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  word TEXT NOT NULL,
  FOREIGN KEY (player_id) REFERENCES user(id)
);
